# Generated by Django 2.0.1 on 2018-01-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('description', models.CharField(max_length=50)),
                ('is_billed_overtime', models.BooleanField()),
                ('is_default', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Billable Item',
            },
        ),
        migrations.CreateModel(
            name='BillRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('overtime_bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Bill Rate',
                'verbose_name_plural': 'Bill Rates',
            },
        ),
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Bill Type',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('department_title', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
