# Generated by Django 2.0.1 on 2018-01-15 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('billing', '0001_initial'),
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='lead_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='billrate',
            name='billable_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_rates', to='billing.BillableItem'),
        ),
        migrations.AddField(
            model_name='billrate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_rates', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='billrate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_rates', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='billableitem',
            name='bill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='billable_items', to='billing.BillType'),
        ),
        migrations.AddField(
            model_name='billableitem',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='billable_items', to='billing.Department'),
        ),
    ]
