# Generated by Django 2.0.1 on 2018-01-11 23:32

import api.models.base_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('is_billed_overtime', models.BooleanField()),
                ('is_default', models.BooleanField()),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel),
        ),
        migrations.CreateModel(
            name='BillRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('overtime_bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('billable_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_rates', to='api.BillableItem')),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel),
        ),
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('cell_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultTaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_title', models.CharField(max_length=20)),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_initial', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=50)),
                ('cell_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_ext', models.IntegerField(blank=True, null=True)),
                ('current_week_start', models.DateField()),
                ('default_bill_rate', models.ManyToManyField(to='api.BillRate')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervised_employees', to='api.Employee')),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('overtime', models.FloatField()),
                ('is_billable', models.BooleanField()),
                ('bill_rate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='api.BillRate')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='api.Employee')),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel, api.models.base_models.ModifiableModel),
        ),
        migrations.CreateModel(
            name='EntryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Entry Statuses',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            bases=(models.Model, api.models.base_models.CreateableModel),
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Invoice Statuses',
            },
            bases=(models.Model, api.models.base_models.CreateableModel),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('requires_afe', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='api.Client')),
                ('lead_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='api.Employee')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='api.Office')),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel),
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Project Statuses',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_subset_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_subsets', to='api.Project')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_subsets', to='api.Contact')),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel),
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('p6_task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_subset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='api.ProjectSubset')),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel),
        ),
        migrations.CreateModel(
            name='TaskEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=50)),
                ('estimated_hours', models.FloatField()),
                ('bill_rate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_estimates', to='api.BillRate')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_estimates', to='api.TaskEstimate')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_estimates', to='api.Task')),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel, api.models.base_models.ModifiableModel),
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Task Statuses',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=50)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
            bases=(models.Model, api.models.base_models.ActivatableModel, api.models.base_models.CreateableModel),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to='api.TaskStatus'),
        ),
        migrations.AddField(
            model_name='projectsubset',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_subsets', to='api.WorkOrder'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='api.ProjectStatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='api.ProjectType'),
        ),
        migrations.AddField(
            model_name='project',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='api.WorkOrder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='api.InvoiceStatus'),
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='api.EntryStatus'),
        ),
        migrations.AddField(
            model_name='entry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='api.Invoice'),
        ),
        migrations.AddField(
            model_name='entry',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='api.Office'),
        ),
        migrations.AddField(
            model_name='entry',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_edtries', to='api.Entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='api.Task'),
        ),
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='api.Office'),
        ),
        migrations.AddField(
            model_name='department',
            name='lead_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='api.Employee'),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='api.Contact'),
        ),
        migrations.AddField(
            model_name='billrate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_rates', to='api.Client'),
        ),
        migrations.AddField(
            model_name='billrate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bill_rates', to='api.Project'),
        ),
        migrations.AddField(
            model_name='billableitem',
            name='bill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='billable_items', to='api.BillType'),
        ),
        migrations.AddField(
            model_name='billableitem',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='billable_items', to='api.Department'),
        ),
    ]
