# Generated by Django 2.0.1 on 2018-01-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lead_employee',
            field=models.ForeignKey(default='3d5b1ae5-fa7f-4031-a6a2-152ba2fe10e9', on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='employees.Employee'),
            preserve_default=False,
        ),
    ]
