# Generated by Django 2.0.1 on 2018-01-12 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20180112_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_edtries', to='entries.Entry'),
        ),
    ]
